In [1]:
import numpy as np

a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
np.linalg.det(a)

59.999999999999986

In [2]:
b = np.linalg.inv(a)
print(b)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [9]:
# Пример матрицы 4х4, ранг которой равен 1

c = np.array([[1, 2, 3, 4], [2, 4, 6, 8], [3, 6, 9, 12], [4, 8, 12, 16]])
print(c)
np.linalg.matrix_rank(c)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


1