In [6]:
import numpy as np

A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B)

<ipython-input-6-2695e7353265>:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [11]:
# как бы мы проверяли через подстановку значений в уравнения
x, y, z = 1.13919353, -0.90498444, -0.9009803
print(f'{x + 2 * y - z} ≈ 1')
print(f'{3 * x - 4 * y} ≈ 7')
print(f'{8 * x - 5 * y + 2 * z} ≈ 12')
print(f'{2 * x - 5 * z} ≈ 7')
print(f'{11 * x + 4 * y-7 * z} ≈ 15')

0.23020494999999996 ≈ 1
7.03751835 ≈ 7
11.83650984 ≈ 12
6.78328856 ≈ 7
15.218053170000001 ≈ 15


In [12]:
# Проверка через подстановку матрицы
np.dot(A, [ 1.13919353, -0.90498444, -0.9009803 ])

array([ 0.23020495,  7.03751835, 11.83650984,  6.78328856, 15.21805317])

In [13]:
# подсчитаем невязку
np.dot(A, [ 1.13919353, -0.90498444, -0.9009803 ]) - B

array([-0.76979505,  0.03751835, -0.16349016, -0.21671144,  0.21805317])

In [16]:
# Функция нормы невязки
def Q(x, y, z):
    return ((np.linalg.norm(np.dot(A, [x, y, z]) - B))**2)
Q(1.13919353, -0.90498444, -0.9009803)

0.7152321111819737