In [39]:
import numpy as np
import scipy.linalg

A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)
E = np.eye(3)

print(f'{A} = A\n\n{P} = P\n\n{L} = L\n\n{U} = U')

[[ 1  2  3]
 [ 2 16 21]
 [ 4 28 73]] = A

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] = P

[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]] = L

[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]] = U


In [37]:
# ПРОВЕРКА

print(f'{np.dot(P.T, A)} = A * P\n')
print(f'{np.dot(L, U)} = L * U\n')
print(f'{np.dot(P.T, A) - np.dot(L, U)} = P * A - L * U\n') 


[[ 4. 28. 73.]
 [ 1.  2.  3.]
 [ 2. 16. 21.]] = A * P

[[ 4. 28. 73.]
 [ 1.  2.  3.]
 [ 2. 16. 21.]] = L * U

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] = P * A - L * U



In [59]:
# Вторая часть из видео: ПРидумать вектор правых частей и решить систему 

A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
B = np.array([16, 56, 33]) 
C = np.concatenate((A, B.T[:,None]), axis = 1)

print(f'Ранг матрицы А = {np.linalg.matrix_rank(A)}, \nРанг расширенной матрицы С = {np.linalg.matrix_rank(C)}, \nРешение системы: \n{np.linalg.solve(A, B)}')

Ранг матрицы А = 3, 
Ранг расширенной матрицы С = 3, 
Решение системы: 
[12.98611111  4.46527778 -1.97222222]
