In [87]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])

C = np.concatenate((A, B.T[:,None]), axis = 1)
print(C)
print(np.linalg.solve(A, B))
#print(np.linalg.lstsq(A, B))
print(f'Ранг исходной матрицы = {np.linalg.matrix_rank(A, 0.0001)} \nРанг расширенной матрицы = {np.linalg.matrix_rank(C, 0.0001)}')

if np.linalg.matrix_rank(A, 0.0001) == np.linalg.matrix_rank(C, 0.0001):
    print(f'Решение системы уравнений:\n{np.linalg.solve(A, B)}')
else:
    print('\nСистема уравнений несовместна и не имеет решений, \nтак как ранг у исходной матрицы и расширенной не равны.')
    print('\nЧтобы система стала совместной (путем преобразования вектора правой части ситемы), надо сохранить ранг исходной матрицы 2, для этого вектор правой части системы должен быть [0, 0, 0]')
    B = np.array([0, 0, 0])
    C = np.concatenate((A, B.T[:,None]), axis = 1)
    print(C)
    print(f'Ранг исходной матрицы = {np.linalg.matrix_rank(A, 0.0001)} \nРанг новой расширенной матрицы = {np.linalg.matrix_rank(C, 0.0001)}')
    print(f'Решение новой системы уравнений:\n{np.linalg.solve(A, B)}')
    #print(np.linalg.lstsq(A, B))


[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]
[ 2.83726777e+16 -5.67453553e+16  2.83726777e+16]
Ранг исходной матрицы = 2 
Ранг расширенной матрицы = 3

Система уравнений несовместна и не имеет решений, 
так как ранг у исходной матрицы и расширенной не равны.

Чтобы система стала совместной (путем преобразования вектора правой части ситемы), надо сохранить ранг исходной матрицы 2, для этого вектор правой части системы должен быть [0, 0, 0]
[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
Ранг исходной матрицы = 2 
Ранг новой расширенной матрицы = 2
Решение новой системы уравнений:
[ 0.  0. -0.]
