In [78]:
# 6. Найдите одно из псевдорешений вырожденной системы: A*X = B
# Попробуйте также отыскать и нормальное псевдорешение.

import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])

Q, R = np.linalg.qr(A)
print(f'{A} = A\n')
print(f'{Q} = Q\n')
print(f'{R} = R\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] = A

[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]] = Q

[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]] = R



In [70]:
print(f'{np.dot(Q, R)} = Q * R = А\n ')
print(f'{np.dot(Q.T, Q)} = Q.T * Q - должна быть единичная матрица\n')

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] = Q * R = А
 
[[ 1.00000000e+00 -5.26517217e-16 -2.55176183e-16]
 [-5.26517217e-16  1.00000000e+00  3.37757775e-16]
 [-2.55176183e-16  3.37757775e-16  1.00000000e+00]] = Q.T * Q - должна быть единичная матрица



In [73]:
R1 = R[:2, :2]
print(f'{R1} = R1\n')

B1 = np.dot(Q.T, B)[:2]
print(f'{B1} = B1 = Q.T * B\n')

X1 = np.linalg.solve(R1, B1)
print(f'{X1} = X1, R1 * X1 = B1')

[[-8.1240384  -9.6011363 ]
 [ 0.          0.90453403]] = R1

[-1.21860576e+01  8.54871729e-15] = B1 = Q.T * B

[1.50000000e+00 9.45096256e-15] = X1, R1 * X1 = B1


In [76]:
X = np.append(X1, 0)
print(f'{X} = X  (к X1 присоединили нулевой элемент)\n')
print(f'{np.linalg.norm(X)} - норма')

[1.50000000e+00 9.45096256e-15 0.00000000e+00] = X  (к X1 присоединили нулевой элемент)

1.4999999999999893 - норма


In [77]:
print(f'{np.linalg.norm(np.dot(A, X) - B)} - рассчет невязки')

1.2247448713915885 - рассчет невязки
