## ПРАКТИЧЕСКОЕ ЗАДАНИЕ

1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [3]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [6]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
print(A)

[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [15]:
U, s, W = np.linalg.svd(A)
print(f'матрица U:\n{U}\n')
print(f'Сингулярные числа - список диагональных элементов s:\n{s}\n')
print(f'матрица W:\n{W}')

матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]

Сингулярные числа - список диагональных элементов s:
[8.82 6.14 2.53]

матрица W:
[[ 0.07  0.72  0.69]
 [-0.37  0.67 -0.65]
 [-0.93 -0.21  0.31]]


In [16]:
V = W.T
print(f'матрица V:\n{V}\n')

матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]



In [35]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print(f'Cингулярные числа в виде матрицы D:\n{D}\n')

Cингулярные числа в виде матрицы D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]



In [21]:
np.dot(V.T, V) #проверка ортогональности

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [50]:
# Проведем проверку
A_result = np.dot(np.dot(U, D), V.T)
A_result = np.round(A_result)
print(f'матрица A_result:\n{A_result}\n')
print(f'матрица A:\n{A}\n')
A == A_result

матрица A_result:
[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]

матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]



array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [57]:
print('Евклидова норма матрицы равна евклидовой норме диагональной матрицы из её сингулярных чисел  𝐷 . Максимальное значение полученного отношения будет равно максимальному сингулярному числу  𝜇𝑚𝑎𝑥 , и, принимая во внимание факт сортировки по убыванию сингулярных чисел, получим:')
A_E = D[0, 0]
print(f'Евклидова норма:  {A_E}')

Евклидова норма матрицы равна евклидовой норме диагональной матрицы из её сингулярных чисел  𝐷 . Максимальное значение полученного отношения будет равно максимальному сингулярному числу  𝜇𝑚𝑎𝑥 , и, принимая во внимание факт сортировки по убыванию сингулярных чисел, получим:
Евклидова норма:  8.824868854820442


Есть также _норма Фробениуса_, определяемая как:

$$\left \| A \right \|_{F}=\sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n}a_{ij}^{2}}.$$

In [83]:
A_F = np.sqrt(np.sum((A)**2))
A_F

11.045361017187261

Когда известно сингулярное разложение матрицы, её норма Фробениуса вычисляется как:

$$\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}.$$

In [85]:
A_F = np.sqrt(np.sum(np.diag(D**2)))
A_F

11.045361017187261

In [88]:
np.linalg.norm(A)

11.045361017187261

In [90]:
np.linalg.norm(A) == A_F

True