## Урок 6. Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.
##### 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832] 
##### Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy Полученные значения должны быть равны. 
##### Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [2]:
import numpy as np

zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

array([ 14035,  25830, 166060, 183800,  18360,  51730,  35262, 135300,
        89520,  91520])

In [5]:
zk = zp * ks
cov_man = zk.mean() - zp.mean() * ks.mean() # Ковариация  - величина , определяющая зависимость двух случайных величин.
cov_man

9157.839999999997

In [10]:
np.cov(zp, ks, ddof = 0) # смещенная ковариация

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [11]:
np.std(zp)

59.115480206118605

In [12]:
np.std(ks)

174.55340157098058

In [17]:
cor_man = 9157.839999999997 / (np.std(zp) * np.std(ks))
cor_man

0.8874900920739158

In [18]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

##### 2. Измерены значения IQ выборки студентов, обучающихся в местных технических вузах: 131, 125, 115, 122, 131, 115, 107, 99, 125, 111. Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [20]:
iq_v = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

In [21]:
iq_v.mean() # выборочное среднее

118.1

In [22]:
np.std(iq_v, ddof = 1) # несмещенное стандартное отклонение

10.54566788359614

In [26]:
z_tabl = 2.26 # для l/2
interval_1 = iq_v.mean() - z_tabl * np.std(iq_v, ddof = 1) / np.sqrt(len(iq_v))
interval_2 = iq_v.mean() + z_tabl * np.std(iq_v, ddof = 1) / np.sqrt(len(iq_v))
print(f'доверительный интервал для математического ожидания с надежностью 0.95: [{interval_1, interval_2}]')

доверительный интервал для математического ожидания с надежностью 0.95: [(110.56327742907362, 125.63672257092637)]


##### 3. Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [27]:
D = 25 # дисперсией генеральной совокупности
n = 27 # Объем выборки
x_mean = 174.2 #  среднее выборочное
z_tabl = 1.96 # накопленное нормальное распределение для 0.05/2 по таблице (надежность 0.95)
int_1 = x_mean - z_tabl * np.sqrt(D / n)
int_2 = x_mean + z_tabl * np.sqrt(D / n)
print(f'доверительный интервал для математического ожидания с надежностью 0.95: [{int_1, int_2}]')

доверительный интервал для математического ожидания с надежностью 0.95: [(172.31398912064722, 176.08601087935276)]
