<a href="https://colab.research.google.com/github/annvorosh/GB/blob/NNetwork/NN_L03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Урок 3. TensorFlow

1. Попробуйте улучшить работу нейронной сети (разобранную на уроке), обучавшейся на датасет Fashion-MNIST


In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

In [ ]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [ ]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [ ]:
train_images.shape

(60000, 28, 28)

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
# нормадтзация данных
train_images = train_images / 255.0

test_images = test_images / 255.0

In [ ]:
# строим модель 3 слоя
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(256, activation='relu'),
    keras.layers.Dense(128, activation='tanh'), # сменили sigmoid на tanh  
    keras.layers.Dense(10, activation='softmax')
])

# Первый слой, tf.keras.layers.Flatten, трасформирует двумерный массив на входе в одномерный массив.
# Получившиеся 784(28 x 28) входных нейрона присоединяем к полносвязному слою из 128 нейронов , которые будут использовать функцию активации relu. В выходном слое будет 10 нейронов, по числу классов, которые он должен предсказывать. В нем будет использоваться функция активации softmax и он будет давать предсказание от 0 до 1, где 1 это стопроцентная вероятность.
# Компиляция модели

# Давайте вспомним ключевые понятия, которые нам понадобяться при компиляции:
# Loss function — меряет как точно работает нейросеть.
# Optimizer — определяет способ корректировки весов.
# Metrics — определяет за какие характеристики будут отражаться в процессе обучения.

In [ ]:
model.compile(optimizer='adamax',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [ ]:
model.fit(train_images, train_labels, epochs=100)

Epoch 1/10


/usr/local/lib/python3.9/dist-packages/keras/backend.py:5585: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 [==============================] - 16s 8ms/step - loss: 0.4826 - accuracy: 0.8290
Epoch 2/10
1875/1875 [==============================] - 11s 6ms/step - loss: 0.3654 - accuracy: 0.8680
Epoch 3/10
1875/1875 [==============================] - 11s 6ms/step - loss: 0.3302 - accuracy: 0.8797
Epoch 4/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.3082 - accuracy: 0.8858
Epoch 5/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2896 - accuracy: 0.8925
Epoch 6/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2736 - accuracy: 0.8981
Epoch 7/10
1875/1875 [==============================] - 10s 6ms/step - loss: 0.2610 - accuracy: 0.9040
Epoch 8/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2502 - accuracy: 0.9081
Epoch 9/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2387 - accuracy: 0.9117
Epoch 10/10
1875/1875 [==============================] - 11s 6ms/step - loss: 0.2297 

In [ ]:
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

print('\nTest accuracy:', test_acc)

313/313 - 1s - loss: 0.3216 - accuracy: 0.8839 - 832ms/epoch - 3ms/step

Test accuracy: 0.883899986743927


ВЫВОДЫ:

Для повышения точности модели, увеличили количество нейронов в скрытых слоях в 2 раза = > Test accuracy: 0.8693000078201294

Для повышения точности модели сменили оптимайзер с adam на adamax = > Test accuracy: 0.8705000281333923 (подбор лучшего оптимайзера проведен в прошлом ДЗ)

Для повышения точности модели добавили функцию активации софтмакс в выходной слой activation='softmax'

2. Постройте нейронную сеть(берем простую линейную сеть, которую разбирали на уроке: меняем число слоев, число нейронов , типы активации, тип оптимизатора) 
на датасет from sklearn.datasets import load_boston.



In [ ]:
boston_housing = keras.datasets.boston_housing

(train_x, train_y), (test_x, test_y) = boston_housing.load_data()

In [ ]:
train_x.shape

(404, 13)

In [ ]:
train_y.shape

(404,)

In [ ]:
test_x.shape

(102, 13)

In [ ]:
test_y

array([ 7.2, 18.8, 19. , 27. , 22.2, 24.5, 31.2, 22.9, 20.5, 23.2, 18.6,
       14.5, 17.8, 50. , 20.8, 24.3, 24.2, 19.8, 19.1, 22.7, 12. , 10.2,
       20. , 18.5, 20.9, 23. , 27.5, 30.1,  9.5, 22. , 21.2, 14.1, 33.1,
       23.4, 20.1,  7.4, 15.4, 23.8, 20.1, 24.5, 33. , 28.4, 14.1, 46.7,
       32.5, 29.6, 28.4, 19.8, 20.2, 25. , 35.4, 20.3,  9.7, 14.5, 34.9,
       26.6,  7.2, 50. , 32.4, 21.6, 29.8, 13.1, 27.5, 21.2, 23.1, 21.9,
       13. , 23.2,  8.1,  5.6, 21.7, 29.6, 19.6,  7. , 26.4, 18.9, 20.9,
       28.1, 35.4, 10.2, 24.3, 43.1, 17.6, 15.4, 16.2, 27.1, 21.4, 21.5,
       22.4, 25. , 16.6, 18.6, 22. , 42.8, 35.1, 21.5, 36. , 21.9, 24.1,
       50. , 26.7, 25. ])

In [ ]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [ ]:
train_y

array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
       17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
       32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
       23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
       12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.5, 24.8, 19.1,
       22. , 14.5, 11. , 32. , 29.4, 20.3, 24.4, 14.6, 19.5, 14.1, 14.3,
       15.6, 10.5,  6.3, 19.3, 19.3, 13.4, 36.4, 17.8, 13.5, 16.5,  8.3,
       14.3, 16. , 13.4, 28.6, 43.5, 20.2, 22. , 23. , 20.7, 12.5, 48.5,
       14.6, 13.4, 23.7, 50. , 21.7, 39.8, 38.7, 22.2, 34.9, 22.5, 31.1,
       28.7, 46. , 41.7, 21. , 26.6, 15. , 24.4, 13.3, 21.2, 11.7, 21.7,
       19.4, 50. , 22.8, 19.7, 24.7, 36.2, 14.2, 18.9, 18.3, 20.6, 24.6,
       18.2,  8.7, 44. , 10.4, 13.2, 21.2, 37. , 30.7, 22.9, 20. , 19.3,
       31.7, 32. , 23.1, 18.8, 10.9, 50. , 19.6,  5. , 14.4, 19.8, 13.8,
       19.6, 23.9, 24.5, 25. , 19.9, 17.2, 24.6, 13

In [ ]:
mean = train_x.mean(axis=0)
std = train_x.std(axis=0)


train_x -= mean
train_x /= std

test_x -= mean
test_x /= std


print(train_x.mean(axis=0))
print(train_x.std(axis=0))

[-1.01541438e-16  1.09923072e-17  1.74337992e-15 -1.26686340e-16
 -5.25377321e-15  6.41414864e-15  2.98441140e-16  4.94653823e-16
  1.12671149e-17 -1.98136337e-16  2.36686358e-14  5.95679996e-15
  6.13920356e-16]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(train_x.shape[1], )),
    keras.layers.Dense(32, activation='relu'),
    # keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(1) 
])



model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_22 (Dense)            (None, 64)                896       
                                                                 
 dense_23 (Dense)            (None, 32)                2080      
                                                                 
 dense_24 (Dense)            (None, 1)                 33        
                                                                 
Total params: 3,009
Trainable params: 3,009
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# model.compile(optimizer='rmsprop',
#               loss=tf.keras.losses.MeanSquaredError(),
#               metrics=['mae'])

# model.compile(
#     optimizer='sgd',
#     loss='mse',
#     metrics=[tf.keras.metrics.MeanSquaredError()])

model.compile(
    optimizer=keras.optimizers.SGD(learning_rate=0.01, momentum=0.0, nesterov=False),
    loss='mse',
    metrics=['mae'])

# model.compile(optimizer='sgd',
#               loss='mse',
#               metrics=[tf.keras.metrics.LogCoshError()])

# model.compile(
#     optimizer='sgd',
#     loss='mse',
#     metrics=[tf.keras.metrics.CosineSimilarity(axis=1)])

In [ ]:
%time
model.fit(train_x, train_y, batch_size = 404, epochs=10)

Streaming output truncated to the last 5000 lines.
Epoch 6597/10000
1/1 [==============================] - 0s 10ms/step - loss: 0.9757 - mae: 0.7982
Epoch 6598/10000
1/1 [==============================] - 0s 13ms/step - loss: 1.0454 - mae: 0.8032
Epoch 6599/10000
1/1 [==============================] - 0s 10ms/step - loss: 1.0022 - mae: 0.8088
Epoch 6600/10000
1/1 [==============================] - 0s 15ms/step - loss: 1.0740 - mae: 0.8126
Epoch 6601/10000
1/1 [==============================] - 0s 10ms/step - loss: 1.0235 - mae: 0.8165
Epoch 6602/10000
1/1 [==============================] - 0s 10ms/step - loss: 1.1011 - mae: 0.8214
Epoch 6603/10000
1/1 [==============================] - 0s 10ms/step - loss: 1.0416 - mae: 0.8245
Epoch 6604/10000
1/1 [==============================] - 0s 10ms/step - loss: 1.0997 - mae: 0.8215
Epoch 6605/10000
1/1 [==============================] - 0s 10ms/step - loss: 1.0271 - mae: 0.8176
Epoch 6606/10000
1/1 [==============================] - 0s 10ms/ste

In [ ]:
# Делаем прогноз. Возвращается копия предсказания в виде одномерного массива
pred = model.predict(test_x).flatten() 

In [ ]:
pred.shape

In [ ]:
# Средний модуль отклонения 

# err = np.mean(abs(pred - test_y))

err = (pred - test_y).sum() / pred.shape[0]
print(err)

In [ ]:
# Предсказание vs правильный ответ
for i in range(10):
  print("Prediction: ", round(pred[i],2), ", Answer: ", round(test_y[i],2), ", mistake: ", round((pred[i] - test_y[i]),2))

3. Измените функцию потерь и метрику для этой задачи. Постройте 10-15 вариантов и сведите результаты их работы в таблицу Опишите, какого результата вы добились от нейросети? Что помогло вам улучшить ее точность?