#### **Задание на повторение материала

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [4]:
import numpy as np
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [5]:
a1 = a.reshape(3, 4)
a1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
a2 = a.reshape(4, 3)
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [7]:
a3 = a.reshape(2, 6)
a3

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [9]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [10]:
a_1 = a.reshape(3, -1)
a_1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
a_2 = a.reshape(4, -1)
a_2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
a_3 = a.reshape(6, -1)
a_3

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
a_4 = a.reshape(-1, 6)
a_4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [14]:
a_5 = a.reshape(-1, 3)
a_5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
##### нет

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [15]:
b0 = np.random.randn(3, 4)
print(b0.size)
b0

12


array([[ 0.15939358, -0.09091061, -0.37758301,  1.50029474],
       [ 1.25298067, -0.91577506,  1.25582725,  0.1919302 ],
       [ 1.41881088, -1.71831221, -0.05076562, -0.1127404 ]])

In [16]:
b1 = b0.flatten()
print(b1.size)
b1

12


array([ 0.15939358, -0.09091061, -0.37758301,  1.50029474,  1.25298067,
       -0.91577506,  1.25582725,  0.1919302 ,  1.41881088, -1.71831221,
       -0.05076562, -0.1127404 ])

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [17]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [18]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

В чем разница не поняла, так как при интервале 2, массивы получаются одинаковыми.

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [19]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [20]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
c = np.vstack((a, b))
print(c.size)
c

10


array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? 

In [22]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [24]:
B = A.dot(At)
print(B.size)
B

16


array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

 Получится ли вычислить обратную матрицу для матрицы B и почему?


In [25]:
DetB = np.linalg.det(B)
if DetB == 0:
    print(f'Так как определитель матрицы B равен: {DetB}, \n то обратную матрицу вычислить нельзя')
else:
    B_inv = np.linalg.inv(B)
    print(f'Обратная матрица B: \n{B_inv}')

Так как определитель матрицы B равен: 0.0, 
 то обратную матрицу вычислить нельзя


Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [39]:
np.random.seed(42)


Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [44]:
c = np.random.randint(0, 16, 16)
c

array([12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [45]:
C = c.reshape((4, 4))
print(C)

[[12 14 10  7]
 [12  4  6  9]
 [ 2  6 10 10]
 [ 7  4  3  7]]


In [46]:
D = B + C * 10
D

array([[125, 154, 123, 102],
       [134,  90, 146, 212],
       [ 43, 146, 249, 312],
       [102, 162, 242, 372]])

In [47]:
DetD = np.linalg.det(D)
if DetD == 0:
    print(f'Так как определитель матрицы D равен: {DetD}, \n то обратную матрицу вычислить нельзя')
else:
    D_inv = np.linalg.inv(D)
    RankD = np.linalg.matrix_rank(D)
    print(f'Определитель матрицы D равен: {DetD}, \nРанг матрицы D равен: {RankD}, \nОбратная матрица D: \n{D_inv}')

Определитель матрицы D равен: -149097600.0, 
Ранг матрицы D равен: 4, 
Обратная матрица D: 
[[ 0.0004711   0.0111539  -0.00253901 -0.00435621]
 [ 0.00957225 -0.01715762 -0.00876527  0.01450486]
 [-0.00167085  0.01408514  0.02130578 -0.02543824]
 [-0.00321078 -0.00474937 -0.0093469   0.01411451]]



Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [51]:
D_inv = D_inv > 0
D_inv

array([[ True,  True, False, False],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [False, False, False,  True]])

In [52]:
D_inv = np.where(D_inv, 1, 0)
D_inv

array([[1, 1, 0, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 0, 0, 1]])

In [53]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  10,   7],
       [ 14,   4,   6, 122],
       [  2,  86, 149,  10],
       [  7,   4,   3, 302]])

In [54]:
B # для проверки элементов

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [56]:
C # для проверки элементов

array([[12, 14, 10,  7],
       [12,  4,  6,  9],
       [ 2,  6, 10, 10],
       [ 7,  4,  3,  7]])