In [14]:
# !pip install torch torchvision

In [15]:
import torch
import torchvision

In [16]:
import numpy as np

In [17]:
torch.__version__

'2.0.0'

**Задачи для практического задания к уроку 1**

1. Создайте случайный FloatTensor размера 3x4x5

In [39]:
a = torch.randn(3, 4, 5).float()
a

tensor([[[ 2.0824, -0.5457,  0.9778,  0.7028,  0.0388],
         [-0.2704,  1.0423,  1.5813, -1.2461,  0.6228],
         [-0.9166, -0.2036, -0.8645,  0.9781,  0.7918],
         [-1.6215, -0.7318, -0.0803, -0.6237, -1.3362]],

        [[-1.8083,  0.2499, -0.2042,  0.3902, -0.1865],
         [-0.0785, -1.8508, -1.3304, -0.8379,  0.3763],
         [-1.6504, -0.7332, -0.2712,  1.2943,  0.2004],
         [-0.8840, -0.1867,  0.1439, -0.8150,  0.3195]],

        [[ 1.1544,  0.5924,  1.9077, -0.3826, -1.9555],
         [-0.6394,  0.0782,  0.6807, -0.6587, -0.8403],
         [ 0.3073,  0.3729, -0.4046,  0.2261, -0.2528],
         [-0.3650, -0.6052,  0.3347, -0.2353, -0.7726]]])

2. Выведите его форму (shape)


In [40]:
a.shape

torch.Size([3, 4, 5])

3. Приведите его к форме 6х10


In [42]:
a = a.reshape(6, 10)
a

tensor([[ 2.0824, -0.5457,  0.9778,  0.7028,  0.0388, -0.2704,  1.0423,  1.5813,
         -1.2461,  0.6228],
        [-0.9166, -0.2036, -0.8645,  0.9781,  0.7918, -1.6215, -0.7318, -0.0803,
         -0.6237, -1.3362],
        [-1.8083,  0.2499, -0.2042,  0.3902, -0.1865, -0.0785, -1.8508, -1.3304,
         -0.8379,  0.3763],
        [-1.6504, -0.7332, -0.2712,  1.2943,  0.2004, -0.8840, -0.1867,  0.1439,
         -0.8150,  0.3195],
        [ 1.1544,  0.5924,  1.9077, -0.3826, -1.9555, -0.6394,  0.0782,  0.6807,
         -0.6587, -0.8403],
        [ 0.3073,  0.3729, -0.4046,  0.2261, -0.2528, -0.3650, -0.6052,  0.3347,
         -0.2353, -0.7726]])

4. Создайте случайный IntTensor размера 10


In [43]:
b = torch.randn(10).int()
b

tensor([0, 0, 1, 0, 0, 0, 0, 1, 0, 1], dtype=torch.int32)

5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [45]:
c = a * b
c

tensor([[ 0.0000, -0.0000,  0.9778,  0.0000,  0.0000, -0.0000,  0.0000,  1.5813,
         -0.0000,  0.6228],
        [-0.0000, -0.0000, -0.8645,  0.0000,  0.0000, -0.0000, -0.0000, -0.0803,
         -0.0000, -1.3362],
        [-0.0000,  0.0000, -0.2042,  0.0000, -0.0000, -0.0000, -0.0000, -1.3304,
         -0.0000,  0.3763],
        [-0.0000, -0.0000, -0.2712,  0.0000,  0.0000, -0.0000, -0.0000,  0.1439,
         -0.0000,  0.3195],
        [ 0.0000,  0.0000,  1.9077, -0.0000, -0.0000, -0.0000,  0.0000,  0.6807,
         -0.0000, -0.8403],
        [ 0.0000,  0.0000, -0.4046,  0.0000, -0.0000, -0.0000, -0.0000,  0.3347,
         -0.0000, -0.7726]])

6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти


In [53]:
c.shape
c.T.mm(c), c.T.mm(c).shape

(tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000],
         [ 0.0000,  0.0000,  5.6216,  0.0000,  0.0000,  0.0000,  0.0000,  3.0113,
           0.0000,  0.3102],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000],
         [ 0.0000,  0.0000,  3.0113,  0.0000,  0.0000,  0.0000,  0.0000,  4.8730,
           0.0000, -0.1930],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000],
 

7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [59]:
x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)
x, z, t


(tensor([1.], requires_grad=True),
 tensor([0.5000], requires_grad=True),
 tensor([2.], requires_grad=True))

In [63]:
y = x ** 3 + z - 75 * t 
y.backward()
y

tensor([-148.5000], grad_fn=<SubBackward0>)

In [64]:
x.grad, z.grad, t.grad

(tensor([9.]), tensor([3.]), tensor([-225.]))

8. Создайте единичный тензор размера 5x6


In [76]:
d = torch.ones(5, 6)
d

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

9. Переведите его в формат numpy

In [77]:
import numpy as np
d = d.numpy()
d

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)